CREATE TABLE lectures (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lectureTitle VARCHAR(255) NOT NULL,
  videoUrl VARCHAR(500),
  publicId VARCHAR(255),
  isPreviewFree BOOLEAN DEFAULT FALSE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


